spring.datasource.url=jdbc:mysql://localhost:3306/bank
spring.datasource.username=root
spring.datasource.password=Dhi@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=truespring.application.name=project-leap-Bank
